server:
  port: 8080
springdoc:
  packages-to-scan: "com.unnamedteam.stuffrent"
  paths-to-match: "/**"
spring:
  servlet:
    multipart:
      max-file-size: 256KB
      max-request-size: 256KB
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres?useSSL=false
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
storage:
  location: ./uploads


