server:
  port: 8080
springdoc:
  packages-to-scan: "com.unnamedteam.stuffrent"
  paths-to-match: "/**"
spring:
  servlet:
    multipart:
      max-file-size: 256KB
      max-request-size: 256KB
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://ec2-63-32-248-14.eu-west-1.compute.amazonaws.com:5432/dqmgu9i274dva
    username: oqkgtucstjeyts
    password: 61a0ef00fa44488f7d48e5dff7e8c4cd1500572f3c5304816103d1e5870febe6
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
storage:
  location: ./uploads


