server:
  port: 8080
springdoc:
  packages-to-scan: "com.unnamedteam.stuffrent"
  paths-to-match: "/**"
spring:
  servlet:
    multipart:
      max-file-size: 256KB
      max-request-size: 256KB
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://ec2-52-208-164-5.eu-west-1.compute.amazonaws.com:5432/dds4qborfslvv8
    username: nmduamqrawmkdr
    password: 06365007cb58fa6f2d1baa8a88eef0d2a4c991d588faab9bc134f1debd8370f1
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
storage:
  location: ./uploads


